---
title: "Assignment 1: Introduction"
author: Natalie von Turkovich
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took Stats last semester with Professor Albright. We had to learn are as we went, it was really hard! By the end of the semester I was feeling comfortable with it. I understand how the systems work generally, but I am working on learning the code to memory so that I can code withtout needing to look up how to do code each command. I have no prior experience with GitHub. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel pretty confident with basic formatting for making knitted documents look nice. I feel like I have a pretty solid understand of how the pieces of these application work together. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: Being given a task and needing to come up with the code without any direction. There is always google, but I want to start to remember how to code things with out having to search every line. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file. 

> Answer: https://github.com/nvonturkovich/Environmental_Data_Analytics_2021.git


